### ISSUE TITLE
IPFS is not resolving: Error verifying IPFS: Error parsing file

### ISSUE THREAD

**Issue by ligi** [dappnode/DNP_ADMIN#430]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **ipfs.dnp.dappnode.eth**: 0.2.7
- **vpn.dnp.dappnode.eth**: 0.2.5
- **wifi.dnp.dappnode.eth**: 0.2.3
- **dappmanager.dnp.dappnode.eth**: 0.2.30, commit: dc8967d2
- **wamp.dnp.dappnode.eth**: 0.2.2
- **bind.dnp.dappnode.eth**: 0.2.4
- **admin.dnp.dappnode.eth**: 0.2.19, commit: 875f5a7b

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.24.1, build 4667896b
- **Disk usage**: 20%

Most things look nice so far - just IPFS gives me some issues:

![Selection_516](https://user-images.githubusercontent.com/111600/82114076-bd7a9680-975a-11ea-92af-55e1d42725fe.png)

but IPFS looks nice and running:

![Selection_517](https://user-images.githubusercontent.com/111600/82114096-e307a000-975a-11ea-9748-45907322a13e.png)

Space is also not the problem:

![Selection_518](https://user-images.githubusercontent.com/111600/82114121-0b8f9a00-975b-11ea-93c1-16b3d48477bc.png)

IPFS size even shows up after a while:
![image](https://user-images.githubusercontent.com/111600/82114177-675a2300-975b-11ea-8636-73b88197bb09.png)

any Idea what I can check next?

**Comment by ligi** [comment]
This might be related as IPFS throws the warnings - so I also add this here:

![Selection_520](https://user-images.githubusercontent.com/111600/82115866-c45ad680-9765-11ea-870c-ccc0b7e03e46.png)

**Comment by vdo** [comment]
Some old domains like decentral.eth work, but others fail to resolve like the mentioned verificat.eth or almonit.eth, probably related with the recent IPFS 0.5.0 update

Should we move this to DNP_DAPPMANAGER @dapplion  ? Is this related with the diagnose error?

**Comment by dapplion** [comment]
@ligi Thanks for reporting. I believe this is caused by a breaking change in the IPFS HTTP API. We've fixed the incompatibility here https://github.com/dappnode/DNP_ADMIN/commit/536b8f2249778f176197fd526aeeae030e93190b which is already released in the latest core version. Please if possible, update your DAppNode and let us know if the error is fixed

**Comment by ligi** [comment]
@dapplion sounds great - thanks! What is the recommended way to update the dappnode to include this fix? I was updating packages already - but not yet the base system and I do not really find a way to do so currently.

**Comment by ligi** [comment]
Great - just updated - @vdo told me the trick.

Diagnose looks good now:

![Selection_541](https://user-images.githubusercontent.com/111600/82657712-1a2bf480-9c26-11ea-9725-31e7b771fbdd.png)

but I am still seeing an issue when trying to visit ens sites:

![Selection_542](https://user-images.githubusercontent.com/111600/82657873-5d866300-9c26-11ea-8041-ff3b27640da8.png)

**Comment by ligi** [comment]
the problem only seems to be when a content record is used like here:
![Selection_544](https://user-images.githubusercontent.com/111600/82659018-46e10b80-9c28-11ea-93f5-4f5f196c7971.png)

@vdo just made me aware it works for dnslink records:

![Selection_543](https://user-images.githubusercontent.com/111600/82659039-4f394680-9c28-11ea-9851-0424f9d32b7b.png)

**Comment by dapplion** [comment]
Thanks! It seems that we are miss assigning IPNS hashes as IPFS hashes. We'll take a look soon and let you know

**Comment by dapplion** [comment]
Fixed with latest release https://github.com/dappnode/DNP_DAPPMANAGER/pull/363
